# Generated by Django 3.2.4 on 2021-06-14 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorEducationModel',
            fields=[
                ('dr_education_id', models.AutoField(primary_key=True, serialize=False)),
                ('dr_degree', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'doctor_education',
            },
        ),
        migrations.CreateModel(
            name='DoctorModel',
            fields=[
                ('dr_id', models.AutoField(primary_key=True, serialize=False)),
                ('dr_name', models.CharField(max_length=50)),
                ('dr_email', models.EmailField(max_length=50, unique=True)),
                ('dr_mobile', models.CharField(max_length=14, unique=True)),
                ('dr_password', models.CharField(max_length=500)),
                ('dr_address', models.CharField(max_length=100)),
                ('dr_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.doctoreducationmodel')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='PharmacyModel',
            fields=[
                ('pharmacy_id', models.AutoField(primary_key=True, serialize=False)),
                ('pharmacy_name', models.CharField(max_length=50)),
                ('pharmacy_email', models.EmailField(max_length=50, unique=True)),
                ('pharmacy_mobile', models.CharField(max_length=14, unique=True)),
                ('pharmacy_password', models.CharField(max_length=500)),
                ('pharmacy_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'pharmacy',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=50, unique=True)),
                ('user_mobile', models.CharField(max_length=14, unique=True)),
                ('user_password', models.CharField(max_length=500)),
                ('user_address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionModel',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=50)),
                ('patient_email', models.EmailField(max_length=50)),
                ('patient_prescription', models.TextField()),
                ('prescription_datetime', models.DateTimeField(auto_now_add=True)),
                ('dr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.doctormodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.usermodel')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='AppointmentModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appointment_datetime', models.DateTimeField()),
                ('status', models.IntegerField(default=0, help_text='0-not accepted, 1-accepted, 2-rejected')),
                ('dr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.doctormodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medapp.usermodel')),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
        migrations.AddIndex(
            model_name='doctormodel',
            index=models.Index(fields=['dr_name'], name='doctor_dr_name_1b9bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='doctormodel',
            index=models.Index(fields=['dr_education'], name='doctor_dr_educ_c0a230_idx'),
        ),
    ]
